// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jackett.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JackettEmpty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JackettEmpty) Reset()         { *m = JackettEmpty{} }
func (m *JackettEmpty) String() string { return proto.CompactTextString(m) }
func (*JackettEmpty) ProtoMessage()    {}
func (*JackettEmpty) Descriptor() ([]byte, []int) {
	return fileDescriptor_1536f45c733c7094, []int{0}
}

func (m *JackettEmpty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JackettEmpty.Unmarshal(m, b)
}
func (m *JackettEmpty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JackettEmpty.Marshal(b, m, deterministic)
}
func (m *JackettEmpty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JackettEmpty.Merge(m, src)
}
func (m *JackettEmpty) XXX_Size() int {
	return xxx_messageInfo_JackettEmpty.Size(m)
}
func (m *JackettEmpty) XXX_DiscardUnknown() {
	xxx_messageInfo_JackettEmpty.DiscardUnknown(m)
}

var xxx_messageInfo_JackettEmpty proto.InternalMessageInfo

type JackettResponse struct {
	Result               []byte   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JackettResponse) Reset()         { *m = JackettResponse{} }
func (m *JackettResponse) String() string { return proto.CompactTextString(m) }
func (*JackettResponse) ProtoMessage()    {}
func (*JackettResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1536f45c733c7094, []int{1}
}

func (m *JackettResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JackettResponse.Unmarshal(m, b)
}
func (m *JackettResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JackettResponse.Marshal(b, m, deterministic)
}
func (m *JackettResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JackettResponse.Merge(m, src)
}
func (m *JackettResponse) XXX_Size() int {
	return xxx_messageInfo_JackettResponse.Size(m)
}
func (m *JackettResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JackettResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JackettResponse proto.InternalMessageInfo

func (m *JackettResponse) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

type JackettSearch struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Trackers             []string `protobuf:"bytes,2,rep,name=trackers,proto3" json:"trackers,omitempty"`
	Categories           []string `protobuf:"bytes,3,rep,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JackettSearch) Reset()         { *m = JackettSearch{} }
func (m *JackettSearch) String() string { return proto.CompactTextString(m) }
func (*JackettSearch) ProtoMessage()    {}
func (*JackettSearch) Descriptor() ([]byte, []int) {
	return fileDescriptor_1536f45c733c7094, []int{2}
}

func (m *JackettSearch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JackettSearch.Unmarshal(m, b)
}
func (m *JackettSearch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JackettSearch.Marshal(b, m, deterministic)
}
func (m *JackettSearch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JackettSearch.Merge(m, src)
}
func (m *JackettSearch) XXX_Size() int {
	return xxx_messageInfo_JackettSearch.Size(m)
}
func (m *JackettSearch) XXX_DiscardUnknown() {
	xxx_messageInfo_JackettSearch.DiscardUnknown(m)
}

var xxx_messageInfo_JackettSearch proto.InternalMessageInfo

func (m *JackettSearch) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *JackettSearch) GetTrackers() []string {
	if m != nil {
		return m.Trackers
	}
	return nil
}

func (m *JackettSearch) GetCategories() []string {
	if m != nil {
		return m.Categories
	}
	return nil
}

func init() {
	proto.RegisterType((*JackettEmpty)(nil), "proto.JackettEmpty")
	proto.RegisterType((*JackettResponse)(nil), "proto.JackettResponse")
	proto.RegisterType((*JackettSearch)(nil), "proto.JackettSearch")
}

func init() { proto.RegisterFile("jackett.proto", fileDescriptor_1536f45c733c7094) }

var fileDescriptor_1536f45c733c7094 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x8f, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x09, 0x55, 0x23, 0x7a, 0x6a, 0x8b, 0x74, 0x40, 0x14, 0x75, 0x40, 0x55, 0xa6, 0xb2,
	0x74, 0x80, 0x85, 0x1d, 0x41, 0x04, 0x63, 0x78, 0x02, 0xe3, 0x1e, 0xc5, 0xfc, 0xb1, 0xc3, 0xf9,
	0x82, 0xe8, 0xb3, 0xf2, 0x32, 0xa8, 0x76, 0x52, 0x35, 0x03, 0x03, 0x93, 0xf5, 0xfb, 0xee, 0xf3,
	0xd9, 0x3f, 0x98, 0xbc, 0x2a, 0xfd, 0x46, 0x22, 0xcb, 0x9a, 0x9d, 0x38, 0x1c, 0x86, 0xa3, 0x98,
	0xc2, 0xf8, 0x21, 0xe6, 0xb7, 0x1f, 0xb5, 0x6c, 0x8a, 0x0b, 0x38, 0x6e, 0xb9, 0x22, 0x5f, 0x3b,
	0xeb, 0x09, 0x33, 0x48, 0x99, 0x7c, 0xf3, 0x2e, 0x79, 0x32, 0x4f, 0x16, 0xe3, 0xaa, 0xa5, 0x42,
	0xc1, 0xa4, 0xad, 0x3e, 0x92, 0x62, 0xfd, 0x82, 0xa7, 0x30, 0xfc, 0x6c, 0x88, 0x37, 0xa1, 0x37,
	0xaa, 0x22, 0xe0, 0x0c, 0x8e, 0x84, 0xb7, 0x3d, 0xf6, 0xf9, 0xe1, 0x7c, 0xb0, 0x18, 0x55, 0x3b,
	0xc6, 0x73, 0x00, 0xad, 0x84, 0xd6, 0x8e, 0x0d, 0xf9, 0x7c, 0x10, 0xa6, 0x7b, 0xc9, 0xe5, 0x4f,
	0x02, 0xd3, 0xdd, 0x1b, 0xfc, 0x65, 0x34, 0x61, 0x09, 0x59, 0x49, 0x81, 0x88, 0x6f, 0x9c, 0x7d,
	0x36, 0xeb, 0x86, 0x95, 0x18, 0x67, 0xf1, 0x24, 0x9a, 0x2d, 0xf7, 0x7d, 0x66, 0x59, 0x3f, 0xec,
	0xa4, 0x8a, 0x03, 0xbc, 0x83, 0xb3, 0x92, 0xa4, 0x5b, 0x41, 0xab, 0x7b, 0xbb, 0xa2, 0xef, 0xed,
	0xa7, 0xfe, 0xb9, 0xe7, 0x1a, 0xd2, 0xce, 0xbf, 0xdf, 0x89, 0xe9, 0xdf, 0x37, 0x9f, 0xd2, 0x30,
	0xb8, 0xfa, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x21, 0x25, 0xe1, 0x9a, 0x01, 0x00, 0x00,
}
